//
// Created by hal9000 on 4/21/24.
//

#ifndef STALKER_STLKR_ENUMERABLEBASESIMD_H
#define STALKER_STLKR_ENUMERABLEBASESIMD_H
namespace STLKR_LinearAlgebra{
    
}
#endif //STALKER_STLKR_ENUMERABLEBASESIMD_H
