# Detect platform + bitness + cache line size.
function(stalker_platform_detect)
    if(UNIX AND NOT APPLE)
        set(STALKER_PLATFORM "LINUX" CACHE STRING "Platform: WINDOWS, LINUX" FORCE)
    elseif(WIN32)
        set(STALKER_PLATFORM "WINDOWS" CACHE STRING "Platform: WINDOWS, LINUX" FORCE)
    else()
        message(FATAL_ERROR "Unsupported platform. Only Windows and Linux are supported.")
    endif()

    if(CMAKE_SIZEOF_VOID_P EQUAL 8)
        set(STALKER_PLATFORM_BITS "64" CACHE STRING "Platform bitness" FORCE)
        set(STALKER_PLATFORM_CACHE_LINE_SIZE "64" CACHE STRING "Cache line size bytes" FORCE)
    else()
        set(STALKER_PLATFORM_BITS "32" CACHE STRING "Platform bitness" FORCE)
        set(STALKER_PLATFORM_CACHE_LINE_SIZE "32" CACHE STRING "Cache line size bytes" FORCE)
    endif()
endfunction()

# Apply platform + bitness compile definitions to a target
function(stalker_platform_apply_defines tgt)
    if(NOT TARGET ${tgt})
        message(FATAL_ERROR "stalker_apply_platform_defines: target '${tgt}' does not exist")
    endif()
    if(STALKER_PLATFORM STREQUAL "WINDOWS")
        target_compile_definitions(${tgt} INTERFACE STALKER_PLATFORM_WINDOWS)
    elseif(STALKER_PLATFORM STREQUAL "LINUX")
        target_compile_definitions(${tgt} INTERFACE STALKER_PLATFORM_LINUX)
    else()
        message(FATAL_ERROR "Unsupported platform: ${STALKER_PLATFORM}")
    endif()
    if(STALKER_PLATFORM_BITS STREQUAL "64")
        target_compile_definitions(${tgt} INTERFACE STALKER_64BIT)
    elseif(STALKER_PLATFORM_BITS STREQUAL "32")
        target_compile_definitions(${tgt} INTERFACE STALKER_32BIT)
    else()
        message(FATAL_ERROR "Unknown bitness value: ${STALKER_PLATFORM_BITS}")
    endif()
    # Always expose cache line size
    target_compile_definitions(${tgt} INTERFACE STALKER_PLATFORM_CACHE_LINE_SIZE=${STALKER_PLATFORM_CACHE_LINE_SIZE})
endfunction()